[tool.poetry]
name = "address-book"
version = "0.1.0"
description = ""
authors = ["R0cke1 <voskoboinyk.mykhailo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
